### ISSUE TITLE
How to set up the thumb of the default location?

### ISSUE THREAD

**Issue by yy1300326388** [djodjoni/MultiSlider#3]
How to set up the thumb of the default location?
Such as I want to set the position of the two thumb to: 20 and 60, my min is 0, Max is 100.
![qq20150703-2 2x](https://cloud.githubusercontent.com/assets/8764899/8497145/674ca316-21ad-11e5-9c43-765635a67128.png)

**Comment by djodjoni** [comment]
you can set default values for thumb 1 and 2 only using parameters: thumbValue1 and thumbValue2
